version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
            - CAR_POSTGRES_TEST_URL: 
    - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci-demo-go
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password
    - image: circleci/redis:latest
        environment:
          container_name: cache_car
    steps:
      - checkout
      - run:
          name: Run Tests
          environment: 
            - REDIS_URL=redis://cache_car
            - CAR_POSTGRES_DEV_URL=postgres://circleci-demo-go:password@localhost:5432/circle_test?sslmode=disable
          command: |
          npm test